### ISSUE TITLE
Enroll cardholders

### ISSUE THREAD

**Issue by bytedreamer** [bytedreamer/Aporta#10]

**Comment by mistial-dev** [comment]
Initially, there's not really much need for formats, and encryption can come along later.

The alarm.com interface allows cards to be either typed in or presented at the reader.  Typing in does get back to formats, so perhaps for the initial implementation it would make sense to only support enroll at door?

**Comment by bytedreamer** [comment]
Decided to enroll the raw bits that are sent from the card that is presented at the reader.
