### ISSUE TITLE
Com Port list is stale

### ISSUE THREAD

**Issue by bytedreamer** [bytedreamer/Aporta#2]
Add or removing com ports doesn't update the list when adding OSDP connections

**Comment by mistial-dev** [comment]
Are you talking about in the UI, or removing devices themselves on the host?

**Comment by bytedreamer** [comment]
COM devices physically attached to the host. For example a USB to RS-485 adapter that had been plug into the port after Aporta started.

**Comment by mistial-dev** [comment]
What platforms are you looking to have notification on?

**Comment by bytedreamer** [comment]
Added a rescan port button

**Comment by mistial-dev** [comment]
That makes sense.
