### ISSUE TITLE
no audio/visual reaction to access denied?

### ISSUE THREAD

**Issue by rsgmodelworks** [bytedreamer/Aporta#34]
It reacts with a beep etc. at the reader when access grant happens.  I didn't see any visual or audio feedback for access denied.  Is this implemented?  If one runs the live Monitor on a browser you see access denied events, so at a bench you can watch either case happen, no problem.

**Comment by mistial-dev** [comment]
What kind of reader?

**Comment by rsgmodelworks** [comment]
This was on OSDP.  Yes I need to confirm this with a trace.  It seemed to not generate feedback with farpointe, wavelynx, or libosdp-conformance as the PD.

**Comment by bytedreamer** [comment]
Added a access denied reader notification for the next release of Aporta. Additionally, there is a
