### ISSUE TITLE
OSDP Driver Configuration screen does not automatically refresh

### ISSUE THREAD

**Issue by rsgmodelworks** [bytedreamer/Aporta#36]
Might be user error I know.  I expected the OSDP Driver Configuration page to automatically update so when I add a device it changes from offline to online.  Apparently you have to refresh the page manually.

**Comment by bytedreamer** [comment]
@rsgmodelworks are you still having this issue. I've not been able to reproduce

**Comment by rsgmodelworks** [comment]
I have not seen this in recent installations.   In my experience it is behaving as intended.
